spring:
    thymeleaf:
        mode: LEGACYHTML5

logging:
    level: debug

server:
    port: 80
    tomcat:
        uri-encoding: UTF-8

fileUploadFolder: /uploaded/

jdbc:
    driver: com.mysql.jdbc.Driver